# Generated by Django 4.2.4 on 2023-08-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo3mf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('material', models.CharField(max_length=50)),
                ('tiempoImpresion', models.TimeField()),
                ('pesoGramos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impresoraModelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('diametroFilamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaDeCompra', models.DateField()),
                ('precioArs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RolloFilamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('fechaDeCompra', models.DateField()),
                ('precioArs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimetroFilamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pesoGramos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
