# Generated by Django 4.2.4 on 2023-08-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppImp3D', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo3mf',
            old_name='impresoraModelo',
            new_name='impresora',
        ),
    ]
